name: build
on: [ push, pull_request ]

jobs:
  golangci:
    name: lint
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'alexeykiselev/nodemon'
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m

  build:
    name: ubuntu
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'alexeykiselev/nodemon'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.17
        uses: actions/setup-go@v3.0.0
        with:
          go-version: 1.17
          check-latest: true
        id: go

      - name: Set up GolangCI-Lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $HOME/bin v1.45.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: make vendor

      - name: Build
        run: export PATH="$HOME/bin:$PATH"; make all

      - name: Test with race detector
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
